### ISSUE TITLE
0install was installed on my computer without permission how do I delete it

### ISSUE THREAD

**Issue by hwalil00** [0install/0install#205] opened 2023-09-25 15:59 UTC
0install was installed on my computer without permission how do I delete it
![image](https://github.com/0install/0install/assets/146012083/59bd6381-6d39-46f7-85e3-7cb114f2b24f)

**Comment by bastianeicher** [comment] 2023-09-25 22:27
Duplicate of 0install/0install-win #196

**Closed** 2023-09-25 22:28 UTC
