### ISSUE TITLE
Signature check race condition on Windows

### ISSUE THREAD

**Issue by bastianeicher** [0install/0install#44] opened 2015-08-12 12:11 UTC
Running a command like `0install select --refresh http://0install.de/feeds/FileZilla.xml` with the OCaml build on Windows sporadically fails with:
```
warning: Failed to clean up GnuPG temporary file '...\Temp\0installa87be1-gpg': Unix.Unix_error(Unix.EACCES, "unlink", "...\\Temp\\0installa87be1-gpg")
warning: Feed http://0install.de/feeds/FileZilla.xml: No signatures found on feed http://0install.de/feeds/cli/netfx.xml!
gpg: can't open `...\Temp\0installa87be1-gpg'
gpg: verify signatures failed: file open error
```
On my machine it fails roughly one out of five times.

Unfortunately activating `--verbose` mode seems to affect the timing and prevent the issue from occurring.

**Comment by talex5** [comment] 2015-08-12 18:39
Very strange. The file must have been created before gpg is invoked: not only does the `temp_file` call not report failure to create it, but `with_file` successfully opens it, writes the data, and closes it again.

Yet gpg claims it failed to open it and unlink gives `EACCESS`. Is the file there at the end? Does it contain the expected contents (the signature data)? Are there any strange permissions with it? Any strange characters in the path (spaces, etc)?

If you wrap gpg with a slower version (e.g. something that sleeps briefly before calling the real executable), does that make it more or less likely to fail? Can you make a dummy gpg executable that tries to read the file and gives a better error about why it fails?

If `with_file` failed to close the channel, I guess we'd see something like this on Windows. But, closing the channel afterwards is the whole point of `with_file`, so that seems unlikely.

**Comment by bastianeicher** [comment] 2015-08-13 16:10
The file is created (e.g. visible briefly in File Explorer) and deleted when when the process ends. There are no unusual characters in the path (ASCII alphanumeric, no spaces). Wrapping gpg with a 2 second sleep did not seem to affect the likelihood of the failure occurring.

I noticed I was only able to reproduce the error with feeds that have at least 1 dependency, causing two or more feeds to be GnuPG checked in short order. Are these checks performed in parallel? Perhaps multiple GnuPG instances accessing the same keyring in `%appdata%\gnupg` is causing the trouble.

**Comment by talex5** [comment] 2015-08-13 17:02
Yes, they run in parallel. Here's a branch which runs them one at a time:
https://github.com/0install/0install/tree/gpg-mutex

**Comment by bastianeicher** [comment] 2015-08-14 13:25
That worked! A build of the branch no longer displays the issue.

**Comment by talex5** [comment] 2015-08-18 14:02
Can you reproduce it with this Python script? It runs 30 gpg subprocesses in parallel. It works for me, though.

    #!/usr/bin/env python2

    import subprocess, tempfile, os

    input_data = 'Test\n'
    sig_data = '''
    -----BEGIN PGP SIGNATURE-----
    Version: GnuPG v2

    iEYEABECAAYFAlXS9XkACgkQb88SG+I5Dgs1vwCfbgWlFdxcDOadLx919sQeIoo5
    b1YAmwamh1wczPTENaKEVOIMjHajcbPs
    =50FM
    -----END PGP SIGNATURE-----
    '''

    tmp_names = []

    def start():
        tmp_fd, tmp_name = tempfile.mkstemp(prefix = 'test-gpg-', dir = './tmp')
        tmp_names.append(tmp_name)

        os.write(tmp_fd, sig_data)
        os.close(tmp_fd)
        child = subprocess.Popen(
                ['gpg',
                 '--no-secmem-warning',
                 '--status-fd', '1',
                 '--keyserver-options', 'no-auto-key-retrieve',
                 '--verify', tmp_name, '-'],
                stdin = subprocess.PIPE)
        return child

    failed = False
    try:
        procs = []
        for _x in range(30):
            procs.append(start())
        for p in procs:
            p.stdin.write(input_data)
        for p in procs:
            p.stdin.close()
            if p.wait():
                print "FAILURE"
                failed = True
    finally:
        for x in tmp_names:
            os.unlink(x)

    if failed:
        raise Exception("FAILED")
    else:
        print "OK"

**Comment by talex5** [comment] 2015-08-18 14:25
And here's the test key to use with the above (import this first):

    -----BEGIN PGP PUBLIC KEY BLOCK-----
    Version: GnuPG v2

    mQGiBD9VwZERBADxb0hM4yKveb/G0NzuznadLsMyvXvgcPHC/gFWEL3JV7gefEal
    RhKOu6VzmBjaC6a2xsZ23//z+p1uvCq4SW7KCrxZAXmIdL4FnYd8n+IU8AgnlmSh
    qbpjuMndbC8PV/leettqUgrBZbMbnbeM0M9VDndtN6/9gesExKELzK0P/wCgjv+G
    6G3bgW4qPuEisfZ+DnO9XQ8EAI/VTM4Y1ZN7Yd3WZwWWlk7OkayxWRzjoRsfgSTL
    AXTItnyubclKbJrO2HGHD508yd4eV0KSD70Pu3DNi8OTDk6auFWNEFxTgi5GSfBY
    /6ghCJLS0wKtA/XkN2HvWf4MDOLcls+lKzJ1sbNFfGbU2kgNhVZQn+K4yC89fSBb
    CCarA/9MVnqECzJ0LitbVpEWYvWrLiqyDJMDBu/bVHF8ZsjWofXGLsjhCLeX1QZB
    mosehmYn4KsihnUJE00Y5G4VdPAKgFqAVhlDldJCl6cBu3VaiGjHLNuyJm/FZjfP
    wx29PxYuuZKtyh+ax6ncsNDW/Ac8uVgjee29KH/UGZIfu2pqlLQcVGVzdGluZyA8
    MGluc3RhbGxAbG9jYWxob3N0PoheBBMRAgAeBQI/VcGRAhsDBgsJCAcDAgMVAgMD
    FgIBAh4BAheAAAoJEG/PEhviOQ4L/cUAnA2HlKWwafeKUdiHQ+P2LPKKcNnFAKCF
    4Y317QsTpF4nfxJPIqFW6CkVP4heBBMRAgAeBQI/VcGRAhsDBgsJCAcDAgMVAgMD
    FgIBAh4BAheAAAoJEG/PEhviOQ4L/cUAn1so0mcZ6tinRJt5iCxn7iHPDqvpAJ4q
    RA8+FJWNI7QL3hl6HqI9bn3DIrkBDQQ/VcGSEAQA4JFAkfn8s3kxCwnWrV80ie79
    QKvRYrshMlmqK4g38vMi5J2A9ZDV7BpgX6kLn3nhemNI+FECsD6f6gwFsoq5Nx6p
    KWZn1x/nzCccdfAvlXsmruZCE5ZMzeK3syQx+b5MHIZ8Ab8cy0PYbzAM3inm8q2C
    IOIFeDP4c/UxbzZFeocAAwUD/0sUksf9adOtDuOxt5ywH8pjlECrTVkm1//m0zHA
    3fuFUyakpfUWhToA7d39Z2AzZp16RbRq+MueBHSmH3VjtP3HVBR35qhlexk+z5fh
    AMIxttimB3SHqsnPi04N25hPgdzefB3jsfKYPEbTzFJEmsHkk7q7r4sT2cMeAEi/
    D/F6iEkEGBECAAkFAj9VwZICGwwACgkQb88SG+I5DgtWIQCfYbMHDZkeEBrxPRbx
    TILMJAHrMUcAn2/FCRQx7NUvKQxmP9MoQTCvTRuO
    =EwA6
    -----END PGP PUBLIC KEY BLOCK-----

**Comment by bastianeicher** [comment] 2015-08-18 16:10
Unfortunately I cannot reproduce the issue with the Python script. It passes with "OK".
I also tried importing the key 30 times in parallel and it also succeeded.

Perhaps something about how OCaml creates temporary files on Windows is not thread-safe?

**Closed** 2015-08-18 19:08 UTC
Labels: bug

**Comment by talex5** [comment] 2015-08-18 19:11
OK, I think I understand what's going on now. If we spawn one "gpg --verify" process while writing the input data for another, the process would inherit the open file descriptor.
On Windows, this would prevent the second instance of gpg from being able to read the file, and prevent 0install from being able to unlink it, until the first process had finished.

**Comment by talex5** [comment] 2015-08-18 19:11
I've committed a fix to master. Does this fix it for you?

**Comment by talex5** [comment] 2015-08-18 19:13
(unfortunately, this change does require OCaml >= 4.01, for the `O_CLOEXEC` flag, so the Windows build machine will need updating)

**Comment by talex5** [comment] 2015-08-19 15:07
I've now committed an alternative fix that doesn't require OCaml 4.01.

**Comment by bastianeicher** [comment] 2015-08-19 16:16
Just tested the old and the new version side-by-side and can confirm the issue is fixed. Thanks. :)

**Comment by talex5** [comment] 2015-08-19 19:16
Great - thanks for confirming!
